### ISSUE TITLE
Allow conducting ballot-comparison audits with mixed ES&S and Dominion CVRs

### ISSUE THREAD

**Issue by benadida** [votingworks/arlo#1442]
ES&S and Dominion CVRs treat overvotes differently, which leads us to having different data entry patterns for both, and thus to not be able to handle states that have mixed-vendor CVRs. We need to fix that.

TBD: how we approach this. Needs a discussion with @jonahkagan and @ginvdr

**Comment by jonahkagan** [comment]
Idea for how to approach this: Special-case ES&S CVRs in the audit math. 
- The audit board audits the ballot normally - e.g. when they see an overvote, they just record all the choices that were voted for
- In the audit math, when we see "overvote" was recorded in the CVR, check to see if the audit board interpretation is also an overvote (we can easily tell because we only support vote-for-1 contests for ES&S).
- Record a discrepancy if the audit board interpretation is not an overvote (maybe +2 to be conservative)
- Do the same for undervotes

**Comment by umbernhard** [comment]
I think this is sound. Idk if there's a reason to hardcode +2, especially if we are taking the audit board's input to be the source of truth. We'll know whether it's +2, +1, or 0 based on who they audit the ballot for.

**Comment by jonahkagan** [comment]
Ah yeah that could work!
