### ISSUE TITLE
AA audit setup workflow: set participating jurisdictions

### ISSUE THREAD

**Issue by mcchilders** [votingworks/arlo#277]
*User Story:*
As an Audit Admin (AA) I need to tell Arlo which jurisdictions will be participating in a particular audit, so that authentication, dashboards, & monitoring features can be provided for each of those jurisdictions individually.

*Background:*
The current version of Arlo assumes that only one jurisdiction is ever participating in the audit. In the new multi-jurisdiction flow, the AA needs to tell us which jurisdictions are participating (aka give us the name of each jurisdiction), and also give us a way to identify the Jurisdiction Admin (JA) for each (aka give us their email address, which will then be used for passwordless, email-token-enabled auth workflow). To facilitate this, the first page in the AA's "audit setup workflow" when they choose to create a new audit is this page.

*Conditions of Acceptance:*
- When the (AA) clicks the "Create New Audit" button on the Create New/View Existing audits landing page, they should be taken to this screen, the first step in the Audit Setup workflow
- This page has the same basic navigation options available on all pages in the AA dashboard:
-- Menu dropdown in the top left 
-- VW logo/Arlo name in the top center 
-- Log out icon/label in the top right
- The audit status box
- Breadcrumbs specific to the AA audit setup workflow
- The "State" label/instruction text/dropdown (prepopulated with all 50 state names, in alpha order)
- The "Audit Participants" label/instruction text/linked sample file download, with:
-- File browser UI if no file uploaded, or if previous upload replaced/failed
(see 1st wireframe)
-- A loading progress bar while a file is uploading indicating file progress (see 2nd wireframe)
-- The filename of the current file, along with a "Replace File" option (see 3rd wireframe), which returns the user to the state with no file uploaded
- "Save and Next" button, which moves the user to the next step in the AA audit setup workflow (spec'd in another card)

*At page load ...*
![Screen Shot 2020-02-24 at 2.11.14 PM.png](https://zube.io/files/votingworks/32767234333c15d47f5bd9090fc0a20d-screen-shot-2020-02-24-at-2-11-14-pm.png)
*While uploading ...*
![Screen Shot 2020-02-24 at 2.11.26 PM.png](https://zube.io/files/votingworks/e1ec211780665d2433adf8a2dc3fa5ac-screen-shot-2020-02-24-at-2-11-26-pm.png)
*After initial upload ...*
![Screen Shot 2020-02-24 at 2.11.58 PM.png](https://zube.io/files/votingworks/66f4842fade157ed84e2bd28e3d8cec1-screen-shot-2020-02-24-at-2-11-58-pm.png)

**Comment by mcchilders** [comment]
Edited to add:
- Replace file instead of Delete File
- Standard file naming ("Audit Participants file") across the page

**Comment by MorganLove** [comment]
@mcchilders 

Some suggestions to make things simpler. for this flow:
- For Screen 2 we don't need a progress bar. The file will load instantly. 
- Make the audit participants flow part of the main audit setup instead of a separate view. We can use breadcrumbs to go between the home page and the audit setup page. 
- The jurisdiction admin would  be excluded from viewing the upload section as a part of their view. But we don't need to make this a completely separate view. However, we can keep the state form for choosing state in readonly, to show the admin that they are part of the correct audit. 
- If we do this then we don't need the menu at all. 
- Can we submit the CSV file and the state selection at the same time instead of in two stages in the first screen when the user clicks the last Save and Next/Launch Audit.

Question:
- Is there a status indicator for jurisdiction admins as well?

**Comment by eventualbuddha** [comment]
@mcchilders Can you provide an example file for this? Would it look like this?

```csv
Jurisdiction,Email
Alameda,brian@voting.works
San Francisco,beau@voting.works
San Francisco,jake@voting.works
Pacifica,morgan@voting.works
…
```

If that's what it is, then we'll need to enforce that jurisdiction name is unique per election. Also, is this the step during which jurisdictions would be created? Anything special we want to do for errors like invalid CSV files?

**Comment by mcchilders** [comment]
@MorganLove 
- RE: progress bar; we don't have to show it if the file loads in under 1 second, I agree. But in my experience even small files can load painfully slowly on dial-up connections, which some users will have. We're also going to have a lot of screens that could reuse this exact same file upload dialog for other, much larger files that definitely will need the progress bar, so my thinking was to include it everywhere so that all these screens can reuse the same element with the same features. Does including it but hiding it if the upload takes less than 1 second sound ok to you?

- RE: making the audit participants step part of the main audit setup flow ... it is? It's the first step in the audit setup flow. I'm not sure if I'm not understanding or your're asking a different question ... can you explain more?

- RE: combining the AA and JA views ... I'm not sure quite what you're asking, but I think they do need to be completely separate, for security reasons? There are different levels of auth for each and different content/workflows in each ... can you say a little bit more about what you want to see and why? Maybe I'm just not understanding. Also not sure what you mean by "state form for choosing state" ... do you mean the create new/view existing audit landing page? The AA user isn't choosing the state/client, there, that is hard-coded as a part of their account creation by us. So we do still need the create new/ view existing audit landing page, regardless, because that just allows the AA to create new audits under their client or access the dashboard/workflow for existing audits they've already created. (Also let's move that discussion to that card, if that's what you're referencing!)

- RE: submit the CSV file and the state selection at the same time, yep, when the user clicks "Save and Next" at the bottom of the page and moves to the next stage in the audit setup workflow (note that this is not the same as launching the audit, deliberately. That comes much later and this data needs to be submitted well before that.)

- RE: Is there a status indicator for JA's as well ... yes, but they're slightly diff. The JA's see the overall audit not started/round x in progess/audit complete status indicators, and then they see jurisdiction-specific statuses but not the global ones.

**Comment by eventualbuddha** [comment]
On the topic of the progress bar, I imagine Morgan intends to implement this where nothing is sent to the server until the user clicks “Save & Next”, and the file is either just selected in a file input or we read it in client-side JavaScript, both of which should be effectively instant.

**Comment by mcchilders** [comment]
@eventualbuddha good call on the sample file, sorry! meant to add that. Here you go![Sample Participating Jurisdictions File - Sheet1.csv](https://zube.io/files/votingworks/199d39f708a9da95b30c2fff20c3fa98-sample-participating-jurisdictions-file-sheet1.csv)

RE: enforcing that jurisdiction name is unique per election, it's actually jurisdiction name + state (from the dropdown) is unique per audit. There will be lots of dupes across audits/states, and that's fine.

RE: errors, yep, we should definitely do that - I was assuming we'd just inherit the same sort of error reporting we currently do for files in the 1-page Arlo workflow, but good to call it out. Added to the CoAs above.

RE: nothing is sent until the user clicks "Save & Next," that's right, but we still shouldn't move the user to the next page in the flow until the file has been successfully sent to the server?

**Comment by eventualbuddha** [comment]
@mcchilders Github seems unhappy about your attachment. Try again?

**Comment by MorganLove** [comment]
> Also not sure what you mean by "state form for choosing state" … do you mean the create new/view existing audit landing page? The AA user isn't choosing the state/client, there, that is hard-coded as a part of their account creation by us.

@mcchilders I'm referencing the 'State' dropdown menu in the mockups above. That is the AA user selecting a state there, right?

RE: Making the audit participants flow part of the main audit setup instead of a separate view. To clarify, the above mockups are referencing a separate page from the rest of the audit setup, instead of simply being a new first section out of the 3+ we have currently. Security does not require it to be a separate page (we're changing what buttons and features are accessible to different levels of access on the same page regardless). 

RE: The landing page. Yes, I'm in agreement that we have the home page that has the 'Create Audit' button (if the logged in user has permission to create an audit) and a list of audits associated with the currently logged in user. We just don't need a navigation menu to access it and the audit setup view if we only have the two views instead of adding in this third one. That's why I was referencing it on this ticket. If we make this part of the audit creation a part of the same view as the rest of the audit setup, it simplifies navigation tremendously.

RE: The upload and 'Save and Next.' @eventualbuddha is correct in what I was thinking. Even if it isn't instant, the uploading of the file would be between forms, which need to wait for the backend to process the data and create the audit anyway. So we can just use the polling setup like we use on the other forms to wait for it to finish before displaying the next form. Implementing an asynchronous file upload that's separate from completing the forms just so we can have progress bars seems to be a relatively major reworking for what might just be overkill.
